import type { Metadata } from "next";
import { Anybody } from "next/font/google";
import "./globals.css";
import { House } from "@/components/House";
import { Canvas } from "@/components/Canvas";
import { Suspense } from "react";
import { cn } from "@/util";
import Link from "next/link";
import { AnimationManager } from "@/components/AnimationManager";
import { Divider } from "@/components/Divider";
import { MenuLink } from "@/components/MenuLink";

const anybody = Anybody({
  subsets: ["latin"],
  axes: ["wdth"],
  // adjustFontFallback: false,
  variable: "--font-main",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={cn([
          "h-full flex flex-col select-none text-white font-sans [font-stretch:150%] overscroll-none",
          "before:bg-background before:fixed before:inset-0 before:-z-10",
          "[--gutter-first:20px]",
          anybody.variable,
        ])}
      >
        <AnimationManager />
        <Canvas>
          <Suspense>
            <House />
          </Suspense>
        </Canvas>
        <div className="text-green px-10 py-4 z-20">
          solving digital problems since 2010
        </div>
        <Divider />
        <div>
          <Link
            href="/"
            className="z-20 relative block text-[108px] font-[850] text-green px-10"
          >
            tghp
          </Link>
        </div>
        <Divider />
        <div className="flex ml-[--gutter-first] border-l border-teal-dark">
          <MenuLink href="/about">about us</MenuLink>
          <MenuLink href="/work">projects</MenuLink>
          <MenuLink href="/contact">connect</MenuLink>
        </div>
        <Divider />
        {children}
      </body>
    </html>
  );
}
